version: '2'
services:
    message-app:
        #文件下载不下来时
        #docker login --username=100006379862 ccr.ccs.tencentyun.com
        #password : videon123
        image: ccr.ccs.tencentyun.com/liujc/XXX:XXX
        volumes:
            - ~/res:/home/work/res
#            - /etc/localtime:/etc/localtime:ro
#            - /etc/timezone:/etc/timezone:ro
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - TZ=Asia/Shanghai
            - APPLICATION_TIO_SERVER=true
            - APPLICATION_TIO_SERVERHOST=0.0.0.0
            - APPLICATION_TIO_PORT=6789
            - SPRING_REDIS_HOST=192.168.1.106
        network_mode: host
        ports:
            - 6789:6789

